name: Build Valhalla Egypt Tiles

on:
  workflow_dispatch:

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build-egypt:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Download Egypt PBF
        run: |
          curl -fL https://download.geofabrik.de/africa/egypt-latest.osm.pbf -o egypt.pbf || exit 1

      - name: Build and Extract Tiles
        run: |
          mkdir -p custom_tiles
          chmod -R 777 .
          
          docker run --rm -v $(pwd):/data ghcr.io/valhalla/valhalla:latest sh -c "
            valhalla_build_config \
              --mjolnir-tile-dir /data/custom_tiles \
              --mjolnir-tile-extract /data/egypt_tiles.tar \
              --mjolnir-timezone /data/custom_tiles/timezones.sqlite \
              --mjolnir-admin /data/custom_tiles/admins.sqlite > /data/valhalla.json && \
            valhalla_build_tiles -c /data/valhalla.json /data/egypt.pbf && \
            valhalla_build_extract -c /data/valhalla.json && \
            chmod -R 777 /data
          "

      - name: Compress and Upload
        if: success()
        run: |
          tar -cvzf egypt_valhalla_data.tar.gz valhalla.json egypt_tiles.tar

      - name: Save Artifact
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: egypt-tiles-package
          path: egypt_valhalla_data.tar.gz
